### ISSUE TITLE
Sorting of songs (in the liked playlist) is different every time

### ISSUE THREAD

**Issue by siggi1984** [OuterTune/OuterTune#13]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/OuterTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

01. Start the APP
02. Go to the like playlist or to the song section
03. The sorting of the songs in the like playlist and in the song section is different every time

### Expected behavior

the sorting should always be the same unless you sort the songs differently in the app, e.g. by playing time, artist, etc. ...

### Actual behavior

X

### Logs

X

### OuterTune version

v0.6.0 Beta 1

### Android version

Android 12

**Comment by mikooomich** [comment]
> Go to the like playlist or to the song section

Does this *only* happen with the automatically provided "Liked songs" playlist?

**Comment by siggi1984** [comment]
> Does this _only_ happen with the automatically provided "Liked songs" playlist?

yes, only with the like playlist and in the song section. 

this doesn't happen with the self-created playlists, they are always correct.

**Comment by mattcarter11** [comment]
@siggi1984 I think this has been fixed in #64. Could you confirm that your problem is the one described there? If so, the request can be closed

**Comment by siggi1984** [comment]
> @siggi1984 I think this has been fixed in #64. Could you confirm that your problem is the one described there? If so, the request can be closed

okay great thank you very much, as soon as the new version is released I will test it and close the problem.

**Comment by siggi1984** [comment]
> @siggi1984 I think this has been fixed in #64. Could you confirm that your problem is the one described there? If so, the request can be closed

At first glance it seems to be fixed.👍👍👍👍
