### ISSUE TITLE
playback stops for cached songs

### ISSUE THREAD

**Issue by siggi1984** [OuterTune/OuterTune#16]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/OuterTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

01. go offline
02. start a song
03. after a few seconds (30-50) the playback stops

### Expected behavior

X

### Actual behavior

X

### Screenshots/Screen recordings

![Screenshot_20240707-162531_OuterTune](https://github.com/DD3Boh/OuterTune/assets/103368536/0dddc63d-e0c8-48c9-80a9-368ed135b3e9)

### Logs

X

### OuterTune version

v0.6.0 Beta 1

### Android version

Android 12

### Additional information

I use the APP logged in to YTM

**Comment by mikooomich** [comment]
Did you listen to the whole song before trying to play it offline? It sound like it caches in fragments/sections, and not all of the fragmentsbgot downloaded

**Comment by siggi1984** [comment]
> Did you listen to the whole song before trying to play it offline? It sound like it caches in fragments/sections, and not all of the fragmentsbgot downloaded

I listened to the song in full and tried it with other songs too.

If you download the songs manually beforehand, it's not a problem. The error only occurs with the cached songs.

**Comment by siggi1984** [comment]
The error occurs when I am logged in to YTM and also when I am not logged in.

**Comment by mikooomich** [comment]
It's because of the caching behaviour changes. I have it (I hope) fixed locally. If you really need it rn, let me know, I could post a commit.

The app is very in-dev, so changes collect in a staging repo, before they periodically get synced here, and it's going to be much longer (baring any critical issues) before they land on the releases page.

**Comment by siggi1984** [comment]
> It's because of the caching behaviour changes. I have it (I hope) fixed locally. If you really need it rn, let me know, I could post a commit.
> 
> The app is very in-dev, so changes collect in a staging repo, before they periodically get synced here, and it's going to be much longer (baring any critical issues) before they land on the releases page.

Everything is fine, no stress. If the error is fixed in the next release then that will be completely sufficient.

Thank you very much for your hard work on this app, which is really great.

**Comment by mikooomich** [comment]
Potential fix: https://github.com/DD3Boh/OuterTune/commit/204b0cf332ce70400ea96312ea589cd7b09a0db9

Close reason: https://github.com/DD3Boh/OuterTune/commit/cd1deb50a36c9d7e9ed826e4186133ca644dc693
