### ISSUE TITLE
More customization options

### ISSUE THREAD

**Issue by sallowgame8** [OuterTune/OuterTune#183]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

There should be more speed options like the ones in innertune for eg 1.15x etc 

### Why do you want this feature?

The song is tooo fast at 1.25x speed

### Additional information

Please add more options from innertune as it's api has been blocked by youtube

**Comment by mikooomich** [comment]
0.7 update
