### ISSUE TITLE
APP crashes in offline mode app

### ISSUE THREAD

**Issue by siggi1984** [OuterTune/OuterTune#2]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/OuterTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

As soon as the cell phone is offline, regardless of the reasons, the APP crashes and you can no longer listen to music.

### Expected behavior

X

### Actual behavior

My Device: Samsung Galaxy a21s, Android 12

### Logs

X

### OuterTune version

latest Debug

### Android version

Android 12

**Comment by DD3Boh** [comment]
Thanks for the report, I managed to reproduce the issue so I will look into it ASAP

**Comment by DD3Boh** [comment]
https://github.com/DD3Boh/OuterTune/commit/877ffe941b8dc473cc9ae1fd06e158700f31182f

Fixed here

**Comment by siggi1984** [comment]
> [877ffe9](https://github.com/DD3Boh/OuterTune/commit/877ffe941b8dc473cc9ae1fd06e158700f31182f)
> 
> Fixed here

Thanks
