### ISSUE TITLE
Unable to play any songs 

### ISSUE THREAD

**Issue by Zaxx69** [OuterTune/OuterTune#21]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/OuterTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

I just opened the latest released version of the app and tried to play a song and the song is not playing at all 

### Expected behavior

If i tap on a song it should play

### Actual behavior

But it doesn't play 

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/1e02c84f-4d19-43fc-b221-5ed3053b5a25

### Logs

But there are no logs 

### OuterTune version

0.6.0. Beta 2

### Android version

13

**Comment by Zaxx69** [comment]
Edit : so i tapped on three dot and tapped on play next and it got fixed

**Comment by mikooomich** [comment]
https://github.com/DD3Boh/OuterTune/commit/8943ade908baeb84d5dc0076b17cc9a5c097b0b3
