### ISSUE TITLE
Stop Music On Task Clear

### ISSUE THREAD

**Issue by AJTechOfficial** [OuterTune/OuterTune#26]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [x] The title of this issue accurately describes the feature request.

### Feature description

Please add an option to enable and disable the option to stop the song when the app is removed from background (like Spotify and InnerTune by z-huang)

### Why do you want this feature?

To make it easier and efficient to stop music 

### Additional information

InnerTune:
![Screenshot_2024-08-28-14-45-44-92_f4703f2d42345ac28c56f11a6100c500](https://github.com/user-attachments/assets/3d4f3a27-4090-43e4-83a7-697281263faa)

**Comment by mikooomich** [comment]
Added for 0.6.0 release
