### ISSUE TITLE
Please add "Fans might also like" feature 

### ISSUE THREAD

**Issue by Hikari2w2** [OuterTune/OuterTune#29]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Please add "Fans might also like" feature, since it's kinda buggy
![Screenshot_2024-08-31-15-49-00-224-edit_com dd3boh outertune](https://github.com/user-attachments/assets/6ae11dfe-a8cc-4553-98fd-3e37bfc6789f)

### Why do you want this feature?

I think it's a very important feature since we can find out new similar artists :)

### Additional information

I love this fork, it's amazing you were able to implement YTM synchronization

**Comment by mikooomich** [comment]
This is actually a bug, see #38

**Comment by mikooomich** [comment]
This is actually a bug, see #38
