### ISSUE TITLE
All Songs From Playlist Not Shown

### ISSUE THREAD

**Issue by anxiouslelimo** [OuterTune/OuterTune#3]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/OuterTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Search for Bollywood
2. Go to Featured Playlist
3. Select the playlist Bollywood Hitlist

### Expected behavior

Should show all the songs in playlist.

### Actual behavior

Only 24 songs are shown instead of 50.

### Logs

Nil

### OuterTune version

Latest Debug

### Android version

Android 11

**Comment by anxiouslelimo** [comment]
https://github.com/Malopieds/InnerTune/issues/95

**Comment by DD3Boh** [comment]
Fixed in dd45f9879a1e987a3483b57b566601c5577af85a, thanks to Malopieds' commit.
Also worth mentioning that you'll need to clear the app data because of database changes, as we don't have a stable database yet since we haven't made the first proper release build yet.
