### ISSUE TITLE
Crash after opening library

### ISSUE THREAD

**Issue by rhaps0dians** [OuterTune/OuterTune#31]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/OuterTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Open app
2. Log in
3. It'll crash

### Expected behavior

Should've worked

### Actual behavior

It didn't

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/f0647424-bbcd-4bd8-a292-e437e7ebb9c0

### Logs

https://pastebin.com/nSwrmNVm

### OuterTune version

0.6.0

### Android version

Android 10

**Comment by atarashiryo** [comment]
earliest build works

**Comment by rhaps0dians** [comment]
okay. what actually happens is when i click library, it would just.... crash??
tried opening it again, still crash
