### ISSUE TITLE
When un-liking a song, it stays in the library

### ISSUE THREAD

**Issue by JoeneckSpoeneck** [OuterTune/OuterTune#33]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/OuterTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Like a Song
Un-Like it

### Expected behavior

When liking the song, it gets added to the library. When un-liking it gets removed from the library.

### Actual behavior

When liking the song, it gets added to the library. When un-liking it stays in the library.

### Logs

I don't really know how to add logs, but I think for this bug, it's not really necessary.

### OuterTune version

0.6.0

### Android version

Android 13

### Additional information

I really like the feature of combining the liked songs and adding them to the library, but it's just a bit annoying that it stays in the library when un-liking it. It would be great if this would be fixed. I don't know, if this really is a bug, but I think it belongs here. It would be great if this could be fixed.

**Comment by mikooomich** [comment]
Restored InnerTune's separation of library in liked, but removing from library also un-likes the song. I'm not sure having inlibrary and liked unified is a good UX design
