### ISSUE TITLE
App crashes when scanning Local Media

### ISSUE THREAD

**Issue by choozn** [OuterTune/OuterTune#35]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/OuterTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Open the App
2. Go to Settings > Local Media
3. Click Scan
4. App crashes after ~15 seconds into scanning

### Expected behavior

The App should not crash.

### Actual behavior

The App crashes. 

I suppose a certain track or the size of my local library (~20GB) causes the scanner to fail.

### Logs

/

### OuterTune version

0.6.0 (21) universal 

### Android version

Android 11

### Additional information

I can provide logs later. I don't have access to logcat right now. Is there a log folder on mobile?

**Comment by mikooomich** [comment]
I'd need logs from logcat, there's many possible causes that would be impossible to debug without

**Comment by materialred** [comment]
I have a very similar issue. It crashes when scanning local library.

Android 15 Beta 
OuterTune 0.6.1 IzzyOnDroid

Here is a logcat:
```*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/husky_beta/husky:15/AP41.240726.010/12266677:user/release-keys'
Revision: 'MP1.0'
ABI: 'arm64'
Timestamp: 2024-09-09 07:35:04.260113483+0200
Process uptime: 47s
Cmdline: com.dd3boh.outertune
pid: 31374, tid: 31436, name: DefaultDispatch  >>> com.dd3boh.outertune <<<
uid: 10604
tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)
pac_enabled_keys: 000000000000000f (PR_PAC_APIAKEY, PR_PAC_APIBKEY, PR_PAC_APDAKEY, PR_PAC_APDBKEY)
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: 'FORTIFY: vsprintf: prevented 21-byte write into 20-byte buffer'
    x0  0000000000000000  x1  0000000000007acc  x2  0000000000000006  x3  00000077c341a150
    x4  2c30311f6364736d  x5  2c30311f6364736d  x6  2c30311f6364736d  x7  7f7f7f7f7f7f7f7f
    x8  00000000000000f0  x9  0000007b195175b8  x10 0000000000000001  x11 0000007b19569410
    x12 0000000066de8908  x13 000000007fffffff  x14 0000000004b358bc  x15 000006b809446e1f
    x16 0000007b195d3048  x17 0000007b195bc570  x18 000000773b5ac000  x19 0000000000007a8e
    x20 0000000000007acc  x21 00000000ffffffff  x22 000000786e333b00  x23 b400007a7f37b590
    x24 0000000000000000  x25 00000077800a20e0  x26 00000077c341da80  x27 b4000078df4850d0
    x28 00000077c341ceb0  x29 00000077c341a1d0
    lr  0000007b19551b28  sp  00000077c341a130  pc  0000007b19551b54  pst 0000000000001000
25 total frames
backtrace:
      #00 pc 000000000005db54  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) (BuildId: f2d672d4e6a2ed452a7f4fb7e9c29da2)
      #01 pc 0000000000061bcc  /apex/com.android.runtime/lib64/bionic/libc.so (__fortify_fatal(char const*, ...)+124) (BuildId: f2d672d4e6a2ed452a7f4fb7e9c29da2)
      #02 pc 000000000009e720  /apex/com.android.runtime/lib64/bionic/libc.so (__vsprintf_chk+144) (BuildId: f2d672d4e6a2ed452a7f4fb7e9c29da2)
      #03 pc 0000000000001348  /data/app/~~__EtnCpiK8zPOmQe7s6wiA==/com.dd3boh.outertune-wRrGGcKIW6H7dibhk5axhg==/base.apk!libffmetaexjni.so (offset 0x53c000)
      #04 pc 000000000000112c  /data/app/~~__EtnCpiK8zPOmQe7s6wiA==/com.dd3boh.outertune-wRrGGcKIW6H7dibhk5axhg==/base.apk!libffmetaexjni.so (offset 0x53c000) (Java_com_dd3boh_ffMetadataEx_FFMpegWrapper_getFullAudioMetadata+756)
      #05 pc 000000000009cf9c  /system/framework/arm64/boot.oat (art_jni_trampoline+124) (BuildId: b59f4d88199871bfb689eb375761faaa041de765)
      #06 pc 000000000077f320  /apex/com.android.art/lib64/libart.so (nterp_helper+4016) (BuildId: dcb9fe2b5c99aa3f1a682a6008427d08)
      #07 pc 0000000000166ff0  [anon:dalvik-classes.dex extracted in memory from /data/app/~~__EtnCpiK8zPOmQe7s6wiA==/com.dd3boh.outertune-wRrGGcKIW6H7dibhk5axhg==/base.apk] (.a.S complex+24)
      #08 pc 000000000077f2c4  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: dcb9fe2b5c99aa3f1a682a6008427d08)
      #09 pc 00000000001ef08a  [anon:dalvik-classes.dex extracted in memory from /data/app/~~__EtnCpiK8zPOmQe7s6wiA==/com.dd3boh.outertune-wRrGGcKIW6H7dibhk5axhg==/base.apk] (H3.p.a+46)
      #10 pc 000000000077e3a4  /apex/com.android.art/lib64/libart.so (nterp_helper+52) (BuildId: dcb9fe2b5c99aa3f1a682a6008427d08)
      #11 pc 00000000001ee372  [anon:dalvik-classes.dex extracted in memory from /data/app/~~__EtnCpiK8zPOmQe7s6wiA==/com.dd3boh.outertune-wRrGGcKIW6H7dibhk5axhg==/base.apk] (H3.j.q+26)
      #12 pc 0000000002013148  /memfd:jit-cache (deleted) (offset 0x2000000) (Z4.a.o+232)
      #13 pc 0000000002006604  /memfd:jit-cache (deleted) (offset 0x2000000) (r5.N.run+1236)
      #14 pc 00000000020344b4  /memfd:jit-cache (deleted) (offset 0x2000000) (Q3.s.run+260)
      #15 pc 0000000000780144  /apex/com.android.art/lib64/libart.so (nterp_helper+7636) (BuildId: dcb9fe2b5c99aa3f1a682a6008427d08)
      #16 pc 00000000004ef3ec  [anon:dalvik-classes.dex extracted in memory from /data/app/~~__EtnCpiK8zPOmQe7s6wiA==/com.dd3boh.outertune-wRrGGcKIW6H7dibhk5axhg==/base.apk] (z5.j.run+4)
      #17 pc 0000000002000c3c  /memfd:jit-cache (deleted) (offset 0x2000000) (z5.a.run+2156)
      #18 pc 0000000000362774  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612) (BuildId: dcb9fe2b5c99aa3f1a682a6008427d08)
      #19 pc 000000000034def0  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+132) (BuildId: dcb9fe2b5c99aa3f1a682a6008427d08)
      #20 pc 00000000009430d8  /apex/com.android.art/lib64/libart.so (art::detail::ShortyTraits<(char)86>::Type art::ArtMethod::InvokeInstance<(char)86>(art::Thread*, art::ObjPtr<art::mirror::Object>, art::detail::ShortyTraits<>::Type...)+60) (BuildId: dcb9fe2b5c99aa3f1a682a6008427d08)
      #21 pc 000000000063e694  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1344) (BuildId: dcb9fe2b5c99aa3f1a682a6008427d08)
      #22 pc 000000000063e144  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallbackWithUffdGc(void*)+8) (BuildId: dcb9fe2b5c99aa3f1a682a6008427d08)
      #23 pc 00000000000701e4  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+132) (BuildId: f2d672d4e6a2ed452a7f4fb7e9c29da2)
      #24 pc 00000000000615a0  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: f2d672d4e6a2ed452a7f4fb7e9c29da2)```

**Comment by domportera** [comment]
I experiencd the same thing on Android 14 - seema to be related to locating album art
[crash-com-dd3boh-outertune-10_09-00-30-34_843.zip](https://github.com/user-attachments/files/16939528/crash-com-dd3boh-outertune-10_09-00-30-34_843.zip)

**Comment by mikooomich** [comment]
@materialred @choozn @domportera  Could one (or all) of you give this build a test and see if it helps? 

https://github.com/DD3Boh/OuterTune/actions/runs/10785573509

**Comment by materialred** [comment]
This Build solves my Problems

**Comment by choozn** [comment]
This Debug Build fixes the crash during scanning but introduces a new one for me. When switching to the "Library" tab after scanning and clicking the "Title" breadcrumb for the first time (=> loading all the scanned songs for the first time), the app crashes. After restarting the app, all the songs loaded for me normally without a crash. I'll try to replicate this.

**Comment by domportera** [comment]
The new build stopped the crash but still doesnt populate the local library - the scan just stops after some time. Clicking Artists shows nothing, clicking Songs crashes

edit: seems like it's not a regression, the old build does this too

1. clear all app data
2. in the Library tab, click songs (it will crash)
3. start up outertunes again and click Library
4. it will probably crash without user input
[crash-com-dd3boh-outertune-debug-10_09-08-30-53_270.zip](https://github.com/user-attachments/files/16944826/crash-com-dd3boh-outertune-debug-10_09-08-30-53_270.zip)
[crash-com-dd3boh-outertune-debug-10_09-08-31-27_289.zip](https://github.com/user-attachments/files/16944827/crash-com-dd3boh-outertune-debug-10_09-08-31-27_289.zip)

**Comment by mikooomich** [comment]
@domportera I need full logcat logs, those don't show anything

**Comment by domportera** [comment]
> @domportera I need full logcat logs, those don't show anything

[outertune10_09-09-27-26_491.log](https://github.com/user-attachments/files/16945562/outertune10_09-09-27-26_491.log)

**Comment by domportera** [comment]
also here's the second time around just clicking Library
[outertune-library-instacrash10_09-09-30-05_538.log](https://github.com/user-attachments/files/16945603/outertune-library-instacrash10_09-09-30-05_538.log)

**Comment by mikooomich** [comment]
I need __***FULL***__ logs. Like I said, those don't show anything. Use adb logcat (so plus into a computer, log to text file, send the text file)
