### ISSUE TITLE
App does not play selected song if its index is big

### ISSUE THREAD

**Issue by OmegaSunkey** [OuterTune/OuterTune#37]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/OuterTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Enter on any playlist or Songlist
2. Try to play any song thats on the position 28 or greater.

### Expected behavior

The selected song should start playing

### Actual behavior

It seems like its trying to access an item thats out of bounds and goes back to index 0 and counts from there again.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/f10ce889-6462-470e-bf76-89d8b6470191

https://github.com/user-attachments/assets/64fa21d6-8d22-4b30-adbb-f82b7c5068af

### Logs

[06_09-10-29-54_522.log](https://github.com/user-attachments/files/16910360/06_09-10-29-54_522.log)
This record was made while switching songs that trigger the bug. I have not switched to a song that does work in this record.

### OuterTune version

0.6.0

### Android version

Android 11, One UI 3.1

### Additional information

This does not happen on InnerTune stable 0.5.10.

I am not able to test on latest debug version since it seems that you have not provided a directory for saving the artifacts GHActions builds.

**Comment by mikooomich** [comment]
What type of playlist is this? I can reproduce on online playlists (ex. community playlists) but not on local playlists. Can you confirm?

**Comment by OmegaSunkey** [comment]
First video is the Songs playlist you get when opening the artist tab.
The second one is just an online playlist.
I haven't tested local playlists as I don't have a lot of songs locally right now.

**Comment by mikooomich** [comment]
Local playlist is just a playlist created from the app itself. you can add all songs of another playlist to it

**Comment by OmegaSunkey** [comment]
I can confirm local playlists don't have this issue.

**Comment by OmegaSunkey** [comment]
Really, thank you!
