### ISSUE TITLE
Duplicate Songs in Playlists and Not All Songs Loaded

### ISSUE THREAD

**Issue by anxiouslelimo** [OuterTune/OuterTune#4]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/OuterTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Search All I Want For Christmas is Pop
2. Open the featured playlist

### Expected behavior

Should open accurate no of songs (161)

### Actual behavior

Only 100 songs are fetched and duplicated multiple times.

### Logs

Nil

### OuterTune version

Latest Debug

### Android version

Android 11

### Additional information

Any tentative dates for a release?

**Comment by DD3Boh** [comment]
This one I can't reproduce, I tried with the playlist you mentioned both logged in and not logged in, it doesn't happen for me

**Comment by anxiouslelimo** [comment]
Tried with the latest debug. Issue does not happen. Closing. Thank you for prompt response. Eagerly waiting for stable release.
