### ISSUE TITLE
Please add auto cache of songs too

### ISSUE THREAD

**Issue by SarveshCRS** [OuterTune/OuterTune#42]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Pls add automatic caching of songs whenever the song is heard so that we don't have to download manually.

### Why do you want this feature?

We can have download option also but auto caching of songs is very useful ( you can set limit in setting as per user's preference)

**Comment by mikooomich** [comment]
This feature was intentionally removed, see #16 or https://github.com/DD3Boh/OuterTune/commit/48399d1842942a75883f8e96bfc628006c2595f5
