### ISSUE TITLE
App crash at launch

### ISSUE THREAD

**Issue by scropion86** [OuterTune/OuterTune#43]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/dd3boh/OuterTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

open the app
the UI is show for few seconds and then crashes 

### Expected behavior

work normally

### Actual behavior

app crash

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/455f3adc-750e-4069-be1b-33c7e56135c9

### Logs

https://pastebin.com/ufYe3s9T

### OuterTune version

0.6.1

### Android version

Android 14

### Additional information

Using Oneplus 10T

**Comment by mikooomich** [comment]
Try this and see if it still crashes 
https://github.com/DD3Boh/OuterTune/actions/runs/10823604307

**Comment by scropion86** [comment]
Working fine now, no crash.

**Comment by mikooomich** [comment]
Duplicate of #35
