### ISSUE TITLE
App crash when clicking on shuffle icon inside the playlist

### ISSUE THREAD

**Issue by SarveshCRS** [OuterTune/OuterTune#44]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/dd3boh/OuterTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Open the player
go to any playlists 
click on the shuffle icon 
player crashes (7/10 times)

### Expected behavior

Shouldn't crash and play the songs

### Actual behavior

crashes and comes back to home screen 

### Logs

N/A

### OuterTune version

0.6.1 hot fix

### Android version

Android 14

**Comment by Hikari2w2** [comment]
Yeah, same issue

**Comment by mikooomich** [comment]
Test with 0.6.2 please. Provide logs (ADB logcats) if it still crashes

**Comment by mikooomich** [comment]
Closing. 0.6.3 should have crashes fixed. Feel free to re-open if this is till an issue
