### ISSUE TITLE
App crashes after restoring InnerTune backup from version 0.5.4 and onward

### ISSUE THREAD

**Issue by Username1-a** [OuterTune/OuterTune#56]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/dd3boh/OuterTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

In OuterTune just restore a backup made from InnerTune version 0.5.4

### Expected behavior

Restoring backup without crashes

### Actual behavior

OuterTune then crashes and it's crashes everytime you try to open it

Just in case, I did restoration on a clean OuterTune (clean installation)

### Logs

[OuterTune Restore - LogFox Crash Log.zip](https://github.com/user-attachments/files/17081874/OuterTune.Restore.-.LogFox.Crash.Log.zip)

### OuterTune version

0.6.2

### Android version

Android 13 QPR3

### Additional information

I know that it may not be a priority, but this is a really great fork and it would be really neat if you could migrate library and playlists from a recent versions of regular InnerTune

InnerTune 0.5.3 backup seems to be restoring without issues, but unfortunately my backup of it is just too old

**Comment by mikooomich** [comment]
Hi. Can you try and see if this fixes the issue? https://github.com/mikooomich/OuterTune/releases/tag/test1

**Comment by Username1-a** [comment]
@mikooomich Thank you very much, now the issue is fixed, restoring properly from IT v0.5.4

**Comment by Username1-a** [comment]
@mikooomich Sorry for bothering, the only issue with restoring from InnerTune I found so far is that you can't add new songs to already previously created playlists, restored from InnerTune – playlists just doesn't appear in "add to playlist" window, there's only option to "create a playlist"

![Screenshot_20240922-180018_Evolution X Launcher](https://github.com/user-attachments/assets/695c5682-6ea6-4710-8a8c-8483f2bb3e73)

**Comment by mikooomich** [comment]
That's likely because playlist are migrated as read-only. You could select all in old playlist, and then add all to a new one
