### ISSUE TITLE
Cached songs also in the offline playlist

### ISSUE THREAD

**Issue by siggi1984** [OuterTune/OuterTune#6]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Would it be possible for the cached songs to also be displayed in the offline playlist.

### Why do you want this feature?

This way we would have all offline songs visible and not just the downloaded ones in a playlist.

**Comment by mikooomich** [comment]
Depends on song cache, see #16
