### ISSUE TITLE
Playback error: Source error (2000): Please sign in

### ISSUE THREAD

**Issue by Rafee-M** [OuterTune/OuterTune#73]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/dd3boh/OuterTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Play a song

### Expected behavior

Song to play normally

### Actual behavior

Sometimes when playing songs, it gives a playback error. This usually goes away after a while, but sometime comes back. Similar behaviour on the original InnerTune app

### Screenshots/Screen recordings

Erorr on OuterTune and Innetune, but no error on InnerTune (fork)

https://github.com/user-attachments/assets/4a768d0e-390e-496a-8d31-867b3154f12f

### Logs

n/a

### OuterTune version

0.6.2

### Android version

Android 13

**Comment by Rafee-M** [comment]
https://github.com/z-huang/InnerTune/issues/1657

https://github.com/z-huang/InnerTune/issues/1654

**Comment by siggi1984** [comment]
I have the same problem

![Screenshot_2024-10-20-20-18-20-856_com dd3boh outertune](https://github.com/user-attachments/assets/c81ea7fb-e850-4327-8a37-b9a9e695b62f)

**Comment by asma019** [comment]
Also same issue

![Screenshot_2024-10-23-00-09-10-38_62b0059fd7c9af64e1365a357d046937](https://github.com/user-attachments/assets/8c0503c1-b1b0-4124-9b5e-ef46815d41a6)

**Comment by rn-297** [comment]
Settings > Content > account > Sign In with your gmail

**Comment by siggi1984** [comment]
> Settings > Content > account > Sign In with your gmail

so in my case it doesn't matter if I'm logged in or not, the song won't play

**Comment by mikooomich** [comment]
Fixed in 0.6.3

**Comment by Shubhamkr4** [comment]
It started happening again, anyone else facing?

**Comment by siggi1984** [comment]
The error has never gone away for me...

**Comment by asma019** [comment]
yes, its happening agein.

**Comment by criticalclear** [comment]
Happened to me rn the only solution i found is to logout my account and it works perfectly fine without an account, idk why

**Comment by mauco81** [comment]
> Happened to me rn the only solution i found is to logout my account and it works perfectly fine without an account, idk why

This made my day too! Thank you

**Comment by chaps369** [comment]
> Happened to me rn the only solution i found is to logout my account and it works perfectly fine without an account, idk why

This method works. Thank you

**Comment by RealDevv** [comment]
The error persists in the OuterTune application, even when logged in, and continues to occur when logged out as well.

![Image](https://github.com/user-attachments/assets/84ac2b0a-17e1-4a44-b91a-ccb2b793d48b)
