### ISSUE TITLE
outertune to yt music transfer

### ISSUE THREAD

**Issue by immortaljam** [OuterTune/OuterTune#78]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

is it possible to transfer music from a playlist made in outertune to yt music?

### Why do you want this feature?

would be very helpful

**Comment by mikooomich** [comment]
You can do this already in app. Log in, create synced playlist, add songs to it

**Comment by immortaljam** [comment]
> You can do this already in app. Log in, create synced playlist, add songs to it

nah that don't work

https://github.com/user-attachments/assets/25d18480-9419-44d1-9590-7d1c8fe11a98

also, I tried waiting asw but it still don't work

**Comment by immortaljam** [comment]
also, after a while the songs which I added to the playlist randomly disappear

https://github.com/user-attachments/assets/9f065379-1629-4b40-bbdb-54fb4e01c18a
