### ISSUE TITLE
Discord Rich Presence

### ISSUE THREAD

**Issue by Boltexx** [OuterTune/OuterTune#85]
### Checklist

- [x] I've checked that there is no other issue about this feature request.
- [x] This issue contains only one feature request.
- [x] The title of this issue accurately describes the feature request.

### Feature description

Discord Rich Presence like Spotify has.

### Why do you want this feature?

It will be really cool.

**Comment by mikooomich** [comment]
Cool feature, but not something for we plan on. Some more info here: https://github.com/z-huang/InnerTune/issues/1392

**Comment by Moondev0607** [comment]
> Some more info here: [z-huang/InnerTune#1392](https://github.com/z-huang/InnerTune/issues/1392)

I think this is no longer an issue. It could be interesting to check the implementation of [PreMiD](https://premid.app/) since they only require a user authentication for their browser client to work.

**Comment by quimodotcom** [comment]
This needs to be reopened asap, would love to see this back as theres a bunch of better rpc than kizzy.
